export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const UPDATE_CART_ITEMS = 'UPDATE_CART_ITEMS'
export const REMOVE_CART_ITEMS = "REMOVE_CART_ITEMS"
export const REMOVE_ALL_ITEMS = "REMOVE_ALL_ITEMS"
export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS"
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD"
export const CART_EMPTY = 'CART_EMPTY'