export const CART_ADD_INGREDIENT = 'CART_ADD_INGREDIENT'
export const REMOVE_CART_INGREDIENT = 'REMOVE_CART_INGREDIENT'
export const UPDATE_CART_INGREDIENT = 'UPDATE_CART_INGREDIENT'
export const CART_INGREDIENT_EMPTY = 'CART_INGREDIENT_EMPTY'
