export const MEAL_LIST_REQUEST = 'MEAL_LIST_REQUEST'
export const MEAL_LIST_SUCCESS = 'MEAL_LIST_SUCCESS'
export const MEAL_LIST_FAIL = 'MEAL_LIST_FAIL'

export const MEAL_REMOVE_REQUEST = 'MEAL_REMOVE_REQUEST'
export const MEAL_REMOVE_SUCCESS = 'MEAL_REMOVE_SUCCESS'
export const MEAL_REMOVE_FAIL = 'MEAL_REMOVE_FAIL'


export const MEAL_CREATE_REQUEST = 'MEAL_CREATE_REQUEST'
export const MEAL_CREATE_SUCCESS = 'MEAL_CREATE_SUCCESS'
export const MEAL_CREATE_FAIL = 'MEAL_CREATE_FAIL'

export const MEAL_DETAILS_REQUEST = 'MEAL_DETAILS_REQUEST'
export const MEAL_DETAILS_SUCCESS = 'MEAL_DETAILS_SUCCESS'
export const MEAL_DETAILS_FAIL = 'MEAL_DETAILS_FAIL'
export const MEAL_DETAILS_RESET = 'MEAL_DETAILS_RESET'

export const MEAL_UPDATE_REQUEST = 'MEAL_UPDATE_REQUEST'
export const MEAL_UPDATE_SUCCESS = 'MEAL_UPDATE_SUCCESS'
export const MEAL_UPDATE_FAIL = 'MEAL_UPDATE_FAIL'

export const MEAL_ONE_REQUEST = 'MEAL_ONE_REQUEST'
export const MEAL_ONE_SUCCESS = 'MEAL_ONE_SUCCESS'
export const MEAL_ONE_FAIL = 'MEAL_ONE_FAIL'

