export const GET_ALL_PROGRAM_REQUEST = 'GET_ALL_PROGRAM_REQUEST';
export const GET_ALL_PROGRAM_SUCCESS = 'GET_ALL_PROGRAM_SUCCESS';
export const GET_ALL_PROGRAM_FAIL = 'GET_ALL_PROGRAM_FAIL';

export const GET_ONE_PROGRAM_REQUEST = 'GET_ONE_PROGRAM_REQUEST';
export const GET_ONE_PROGRAM_SUCCESS = 'GET_ONE_PROGRAM_SUCCESS';
export const GET_ONE_PROGRAM_FAIL = 'GET_ONE_PROGRAM_FAIL';

export const DEL_PROGRAM_REQUEST = 'DEL_PROGRAM_REQUEST';
export const DEL_PROGRAM_SUCCESS = 'DEL_PROGRAM_SUCCESS';
export const DEL_PROGRAM_FAIL = 'DEL_PROGRAM_FAIL';

export const CREATE_ONE_PROGRAM_REQUEST = 'CREATE_ONE_PROGRAM_REQUEST';
export const CREATE_ONE_PROGRAM_SUCCESS = 'CREATE_ONE_PROGRAM_SUCCESS';
export const CREATE_ONE_PROGRAM_FAIL = 'CREATE_ONE_PROGRAM_FAIL';

export const PROGRAM_UPDATE_REQUEST = 'PROGRAM_UPDATE_REQUEST';
export const PROGRAM_UPDATE_SUCCESS = 'PROGRAM_UPDATE_SUCCESS';
export const PROGRAM_UPDATE_FAIL = 'PROGRAM_UPDATE_FAIL';


